### ISSUE TITLE
Returning 0 becomes null

### ISSUE THREAD

**Issue by Nikamura** [yaacovCR/graphql-tools-fork#10]
I have a field that's an Int and when the value is 0 it is returned as null which throws an error ```[[GraphQLError: Cannot return null for non-nullable field MyObject.myNumber.]]``` when the value is any other number it works correctly.

**Comment by yaacovCR** [comment]
Is this in combination with stitching? Can you share an example schema just to make clear? Thanks!

**Comment by yaacovCR** [comment]
This line should not be checking for falsy, but rather for loose equality with null.

https://github.com/yaacovCR/graphql-tools-fork/blob/master/src/stitching/checkResultAndHandleErrors.ts#L49

**Comment by yaacovCR** [comment]
This should be fixed in v6.1.4.
