### ISSUE TITLE
Broken Import path in `transformSchema.ts`

### ISSUE THREAD

**Issue by ghost** [yaacovCR/graphql-tools-fork#23]
After upgrading to the latest `graphql-tools-fork` version. 
I am getting the following error for `transformSchema` import. The error as below: 

Ref for broken import - https://github.com/yaacovCR/graphql-tools-fork/blob/master/src/transforms/transformSchema.ts#L2
```
Cannot find module './utils/SchemaDirectiveVisitor' from 'makeExecutableSchema.js'
   'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].
```

graphql-tools-fork version - 6.4.2

**Comment by yaacovCR** [comment]
Hmmm. Not sure what might be wrong there as paths look ok at first glance. Would deleting any incremental typescript build help?

**Comment by ghost** [comment]
I set up a separate repo with no additional ts-config to test this issue. 
Here is my repo [link](https://github.com/ayemonchit/graphql-import-failing). 

I am still getting broken import errors. This time even more. 

```
node_modules/graphql-tools-fork/dist/index.d.ts:6:15 - error TS2307: Cannot find module './utils'.

6 export * from './utils';
                ~~~~~~~~~

node_modules/graphql-tools-fork/dist/Interfaces.d.ts:2:40 - error TS2307: Cannot find module './utils/SchemaDirectiveVisitor'.

2 import { SchemaDirectiveVisitor } from './utils/SchemaDirectiveVisitor';
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/graphql-tools-fork/dist/Interfaces.d.ts:3:31 - error TS2307: Cannot find module './utils/SchemaVisitor'.

3 import { SchemaVisitor } from './utils/SchemaVisitor';
                                ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/graphql-tools-fork/dist/stitching/mergeSchemas.d.ts:3:40 - error TS2307: Cannot find module '../utils/SchemaDirectiveVisitor'.

3 import { SchemaDirectiveVisitor } from '../utils/SchemaDirectiveVisitor';
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 4 errors.
```

**Comment by yaacovCR** [comment]
Will check later, but my only guess is entire build corrupted for whatever reason. Can you check your node modules folder for those files?

**Comment by yaacovCR** [comment]
Or maybe try using a similar tsconfig as to the one used in the package itself and see if that helps.

**Comment by yaacovCR** [comment]
Burned by npmignore file, will fix tonight hopefully...

Thanks!

**Comment by yaacovCR** [comment]
Hopefully v6.4.3 works!
