### ISSUE TITLE
Stitched schema errors are replaced with another one

### ISSUE THREAD

**Issue by chess777** [yaacovCR/graphql-tools-fork#31]
I'm using graphql-tools-fork v7.2.3
NodeJS v12.8.1, tried also on v13.3.0

I have a following schema:
```
schema {
    mutation: Mutation
}

type Mutation {
    myOperation(input: ID!): ID!
}
```

When I'm resolving mutation I get an error and get following response from GraphQL server:
```
{
  "errors": [
    {
      "message": "Person does not exist",
      "locations": [],
      "path": [
        "myOperation",
        "persons",
        "0",
        "id"
      ],
      "extensions": {
        "code": "ValidationError",
        "severity": "ERROR",
      }
    }
  ],
  "data": null
}
```

Next - this response gets to the service that stitched mentioned schema and I receive following response:
```
{
	"name": "GraphQLError",
	"message": "ID cannot represent value: { person: { 0: [Object] } }",
	"locations": [],
	"path": [
		"myOperation"
	],
	"originalError": {
		"stack": "TypeError: ID cannot represent value: { person: { 0: [Object] } }\n    at GraphQLScalarType.serializeID [as serialize] (<Path>\\node_modules\\graphql\\type\\scalars.js:223:9)\n    at completeLeafValue (<Path>\\node_modules\\graphql\\execution\\execute.js:635:37)\n    at completeValue (<Path>\\node_modules\\graphql\\execution\\execute.js:579:12)\n    at completeValue (<Path>\\node_modules\\graphql\\execution\\execute.js:557:21)\n    at <Path>\\node_modules\\graphql\\execution\\execute.js:492:16\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
		"message": "ID cannot represent value: { person: { 0: [Object] } }"
	},
	"extensions": {
		"code": "INTERNAL_SERVER_ERROR"
	}
}
```

The error was lost and replaced to other error. 
This might be related to the path in error being:
```
[
        "myOperation",
        "persons",
        "0",
        "id"
]
```
But why it tries to go further if `data` is null in the first place?

**Comment by yaacovCR** [comment]
Seems like you are stitching to remote schema with a different schema using transforms?

I think your transform needs to modify the error path so it can be properly recreated. Would you mind sharing the delegation and transform code?

Error proxying works by attempting to reconstruct a response even when null so multiple errors can be passed by gateway, all with correct paths.

**Comment by yaacovCR** [comment]
I am working on adding support for this to WrapType and ExtendSchema related transforms...

**Comment by chess777** [comment]
No, I'm not using transformation. This path comes from backend.

**Comment by yaacovCR** [comment]
Maybe you should be using a transform? I am not quite certain without seeing more code. Is there a reason that path does not match your schema?

**Comment by yaacovCR** [comment]
Actually, tests show already working for WrapType.

**Comment by yaacovCR** [comment]
Very interested in this. If you could share a detailed code sample, that would be amazing.

**Comment by chess777** [comment]
Ok, I understand. It seems I can't just add arbitrary path that does not correspond to schema for errors when stitching as this breaks error matching to properties.

**Comment by yaacovCR** [comment]
Correct, I believe this is as per spec: https://graphql.github.io/graphql-spec/draft/#sec-Errors

You should be able to add whatever you want to error under extensions key.

**Comment by chess777** [comment]
Thanks for help!
Your help is invaluable
