### ISSUE TITLE
Test with graphql-js v15.0.0-rc.1

### ISSUE THREAD

**Issue by IvanGoncharov** [yaacovCR/graphql-tools-fork#32]
Hi @yaacovCR 
I plan to release long overdue graphql-js v15.0.0
It includes a number of small breaking changes:
https://github.com/graphql/graphql-js/releases/tag/v15.0.0-alpha.1
https://github.com/graphql/graphql-js/releases/tag/v15.0.0-alpha.2
https://github.com/graphql/graphql-js/releases/tag/v15.0.0-rc.1

Since your fork uses a lot of public APIs from `graphql-js` it would be great if you can try `15.0.0-rc.1` and report back problems if any.

**Comment by yaacovCR** [comment]
@IvanGoncharov,

One change that I think will be breaking for graphql-tools (now "fixed" in the fork's v15 branch) is that buildSchema used to ignore extensions, but now parses them. graphql-tools used to pass the extensions to buildSchema and then call extendSchema, but in v15 this will fail as the extensions are already added.

https://github.com/graphql/graphql-js/pull/2248
https://github.com/graphql/graphql-js/pull/2246

This is labelled as a new feature (which it is!) but possibly should also be considered a breaking change, which it will be for graphql-tools (although not the fork).

If that makes sense!

**Comment by yaacovCR** [comment]
@IvanGoncharov, looks good from here.

https://github.com/yaacovCR/graphql-tools-fork/commit/a3aadcf368b6495c03c73cf6ae613222b3acede3

**Comment by yaacovCR** [comment]
@IvanGoncharov, looks good from here.

https://github.com/yaacovCR/graphql-tools-fork/commit/a3aadcf368b6495c03c73cf6ae613222b3acede3

Users can install the prerelease of graphql-tools-fork v9 with graphql v15.0.0-rc.1 support via npm using the below amazing label:

```
npm install graphql-tools-fork@9.0.0-graphql-15.0.0-rc.1.0
```

Ref: https://github.com/graphql/graphql-js/issues/2303

**Comment by IvanGoncharov** [comment]
> This is labelled as a new feature (which it is!) but possibly should also be considered a breaking change, which it will be for graphql-tools (although not the fork).

@yaacovCR Yes, indeed 👍 I will update the changelog to mark it as breaking.
It sad that it will break "official" `graphql-tools` but I don't see any good long term solution.
I will ping the Apollo team to see if they can fix it.

**Comment by yaacovCR** [comment]
While you are at it, you could have them just merge in https://github.com/apollographql/graphql-tools/pull/1206
