### ISSUE TITLE
applySchemaTransforms not called in delegateToSchema

### ISSUE THREAD

**Issue by alexander-alvarez** [yaacovCR/graphql-tools-fork#38]
Hi,

Thanks for maintaining this fork. 

I was working through some things and wanted to use some of the built-in transforms provided and I came across an issue when using [`RenameObjectFields`] which uses `TransformObjectFields` which in turn requires [a call to `transformSchema`] to sets up state to be used in [`transformRequest`].

As such using the transformers crashes and burns when calling `delegateToSchema`

Am using these correctly?

( I am passing `RenameObjectFields` directly to the `transforms` of `delegateToSchema` as I only want to apply the ObjectFields transform on a particular query currently)

[`RenameObjectFields`]: https://github.com/yaacovCR/graphql-tools-fork/blob/master/src/transforms/RenameObjectFields.ts#L10
[a call to `transformSchema`]: https://github.com/yaacovCR/graphql-tools-fork/blob/master/src/transforms/TransformObjectFields.ts#L58-L59
[`transformRequest`]: https://github.com/yaacovCR/graphql-tools-fork/blob/master/src/transforms/TransformObjectFields.ts#L71-L83

**Comment by yaacovCR** [comment]
For an intro to transforms, see: https://github.com/yaacovCR/graphql-tools-fork/issues/24#issuecomment-538026894

**Comment by yaacovCR** [comment]
RenameObjectFields is a type "B" transform ie a true schema transform not just request response middleware. It can only be used inside mergeSchemas, transformSchema, wrapSchema.

**Comment by yaacovCR** [comment]
Take a look at tests for examples.

**Comment by yaacovCR** [comment]
You can still accomplish this for a single query by delegating to a subschema made by transformSchema or wrapSchema

**Comment by alexander-alvarez** [comment]
Thank you for the detailed description. I had come to realize this after stepping through all the code but your explanation helps clarify it a lot. sorry for the noise

**Comment by yaacovCR** [comment]
Happy to help. To clarify, you can use these transforms within delegateToSchema like when you are stitching on gateway, but they should be the same group of transform objects passed to mergeSchemas so that state is saved there.

Let me know if I can be of any additional help!
