### ISSUE TITLE
Test with graphql-js v15.0.0-rc.2

### ISSUE THREAD

**Issue by IvanGoncharov** [yaacovCR/graphql-tools-fork#40]
@yaacovCR Thanks a lot for feedback about RC1 👍 
I release RC2: https://github.com/graphql/graphql-js/releases/tag/v15.0.0-rc.2
If you have time can you please test it?

**Comment by yaacovCR** [comment]
Yes! Congrats!

Hopefully over the next few days will update branch.

**Comment by IvanGoncharov** [comment]
@yaacovCR Sounds great 👍 I already promised that it will be the last batch of breaking changes so if everything goes smooth next release would be `15.0.0`.

**Comment by yaacovCR** [comment]
released as graphql-tools-fork@9.0.0-graphql-15.0.0-rc.2.0 a bit prematurely, some failing tests, but two are related to the order the schema is printed i believe not matching test expectation, known breaking change/improvement.

Last one I am not so sure.

There were additional linting changes.

Also graphql-tools upstream will need to be updated to refer to printSchema.js instead of SchemaPrinter when it reaches into internal export

But looks ok!!

**Comment by yaacovCR** [comment]
You can install support for v15 rc2 with:

```
npm install graphql-tools-fork@graphl-15.0.0-rc.2
```

**Comment by yaacovCR** [comment]
https://github.com/yaacovCR/graphql-tools-fork/commit/bb02f68aad13526155c119ef50e959dbf0646afa

**Comment by yaacovCR** [comment]
@IvanGoncharov , FYI I also had to remove node 8 support only this go around. I see no longer supported in graphql-js, but was working anyway in rc1.

In rc2, all subscription stuff failed with v8. Having said that, I am not sure that rc2 itself required removing v8 support, as I also did a fresh install and possibly another dependency received a minor update that broke it

**Comment by yaacovCR** [comment]
@IvanGoncharov 

More careful review of above shows that change in 
https://github.com/graphql/graphql-js/commit/23b427cacc3a6d16eb985ea3e5ab9b47d7a295d0#diff-824b72afd8ba7cd9703ec9cf944ab81a

causes TypeScript to be unable to parse the return type of getNullableType when passing in a parameter of type GraphQLType.

This can be fixed, I think, by changing the definition of:

```
export type GraphQLType =
  | GraphQLScalarType
  | GraphQLObjectType
  | GraphQLInterfaceType
  | GraphQLUnionType
  | GraphQLEnumType
  | GraphQLInputObjectType
// from:
//  | GraphQLList<any>
//  | GraphQLNonNull<any>;
// to:
  | GraphQLList<GraphQLType>
  | GraphQLNonNull<GraphQLType>;
```

Parallel changes can be made elsewhere, for example:

```
export type GraphQLNullableType =
  | GraphQLScalarType
  | GraphQLObjectType
  | GraphQLInterfaceType
  | GraphQLUnionType
  | GraphQLEnumType
  | GraphQLInputObjectType
//  from:
//  | GraphQLList<any>;
//  to:
  | GraphQLList<GraphQLType>;
```

**Comment by yaacovCR** [comment]
I am also able to make this change on my version of TypeScript:

```
export type GraphQLOutputType =
  | GraphQLScalarType
  | GraphQLObjectType
  | GraphQLInterfaceType
  | GraphQLUnionType
  | GraphQLEnumType
// ADD:
//  | GraphQLList<GraphQLOutputType>
//  | GraphQLNonNull<GraphQLOutputType>;
// REMOVE:
//  | GraphQLList<any>
//  | GraphQLNonNull<
//      | GraphQLScalarType
//      | GraphQLObjectType
//      | GraphQLInterfaceType
//      | GraphQLUnionType
//      | GraphQLEnumType
//      | GraphQLList<any>
//    >;
```

Comment above that portion of code notwithstanding, looking like TypeScript is allowing recursive type definitions...

**Comment by yaacovCR** [comment]
Released support in v8.6.0.

**Comment by IvanGoncharov** [comment]
@yaacovCR Thanks for the investigation 👍 
Sadly changes that you proposed breaks pre-3.7 TS versions:
![image](https://user-images.githubusercontent.com/8336157/74660543-53367200-51bc-11ea-9352-a6324b856fee.png)
So simplest solution would be to partially revert https://github.com/graphql/graphql-js/commit/23b427cacc3a6d16eb985ea3e5ab9b47d7a295d0#diff-824b72afd8ba7cd9703ec9cf944ab81a

Long term plan: After TS rewrite we can increase minimal supported version to `3.4` and use https://github.com/sandersn/downlevel-dts

**Comment by yaacovCR** [comment]
Gotcha.
