### ISSUE TITLE
RenameTypes + RenameObjectFields with interface resolveType not transforming correctly

### ISSUE THREAD

**Issue by m-sanders** [yaacovCR/graphql-tools-fork#43]
Hello. We have been using this fork for a while now, and I would like to thank you for keeping Stitching going! 

I posted an issue a while back #27 around schema transforms and I think I have ran into another issue with applying multiple transforms. We're using Prismic, a headless CMS with a GraphQL API, along with schema stitching. We're renaming types and object fields to make their API consistent with ours and to avoid naming conflicts. However I have ran into an issues where the transforms are not mapped correctly.

Here is a simplified version our transforms:

```
const schema = transformSchema(fakeRemoteSchema, [
  new RenameTypes(
    name => (name.startsWith("_") ? name : `P${pascalize(name)}`),
    {
      renameBuiltins: false,
      renameScalars: false
    }
  ),
  new RenameObjectFields((typeName, fieldName) => {
    if (typeName === "Query") return fieldName;

    // Remote uses leading underscores for special fields. Leave them alone.
    if (fieldName[0] === "_") return fieldName;

    // This issue appears to be with renaming `a_item`
    // if (fieldName === "a_item") return fieldName;

    return camelize(fieldName);
  })
]);
```

When querying on a renamed object field on a renamed interface implementation type e.g. `aTransformedObjectField { ... on SomeInterface { field } }`, we receive `null` rather than the data. 

Please find a repo reproducing the issue here: https://github.com/m-sanders/graphql-tools-fork-43

**Comment by yaacovCR** [comment]
Will look into this hopefully next week, reproduction is invaluable. Thanks!

**Comment by yaacovCR** [comment]
I believe there is an expected issue in terms of interfaces, as mapping is by type name, not interface name.

If that is the case, this should be able to be demonstrated using just RenameObjectFields. Are you sure the problem also has to do with RenameTypes?

If I am correct, can you update reproduction?

Thanks for bringing up interfaces. I wonder if it might be straightforward to support them...

**Comment by yaacovCR** [comment]
Will check this out hopefully next week, thank you for reproduction.

**Comment by yaacovCR** [comment]
I think the issue was just with nested object types, I don't think it had anything to do with interaction between RenameObjectFields and RenameTypes, or with the use of interfaces.

Should have been modifying AST via visit when leaving nodes rather than entering.

**Comment by yaacovCR** [comment]
Thanks for the reproduction, which made debugging this much easier. Let me know if this uncovers any additional bugs or I can be of any more help.

**Comment by m-sanders** [comment]
Thanks again @yaacovCR  I will look to complete the update later this week and get back to you if I encounter any other issues.
